# Собираем информацию о координатах магазинов и расстоянию и длительности пути между ними используя Google API

In [1]:
 pip install -U googlemaps

  Created wheel for googlemaps: filename=googlemaps-4.4.1-py3-none-any.whl size=37817 sha256=8307d0e47f6c5f10d16e1d630888b42a2c2629c7b7f2cbcee65e269afd1dd3ea
  Stored in directory: /Users/bond/Library/Caches/pip/wheels/59/eb/61/bba46c3c7dcb0866d48fd67a0c406cc54b80559613449e25e5
Successfully built googlemaps
  Attempting uninstall: googlemaps
    Found existing installation: googlemaps 4.2.2
    Uninstalling googlemaps-4.2.2:
      Successfully uninstalled googlemaps-4.2.2
Note: you may need to restart the kernel to use updated packages.


In [5]:
import pandas as pd
import googlemaps
from itertools import tee
import numpy as np

In [6]:
#reading csv file with adresses
df_adress = pd.read_csv('5_adresses.csv')

In [7]:
df_adress.head(20)

part1  part2  part3
0             16-я Парковая улица    NaN    NaN
1          1-й Паловский переулок    NaN    NaN
2        1-я Аэропортовская улица    NaN    NaN
3          1-я Владимирская улица    NaN    NaN
4              1-я Вольская улица    NaN    NaN
5          1-я Останкинская улица    NaN    NaN
6   26 Бакинских Комиссаров улица    NaN    NaN
7         2-й Стрелецкий переулок    NaN    NaN
8            2-й Тушинский проезд    NaN    NaN
9          2-я Владимирская улица     19    NaN
10         2-я Владимирская улица     21    NaN
11       2-я Звенигородская улица    NaN    NaN
12            2-я Кабельная улица    NaN    NaN
13         2-я Останкинская улица    NaN    NaN
14          3-я Гражданская улица    NaN    NaN
15        40 лет Октября проспект     19    NaN
16        40 лет Октября проспект      4    NaN
17           4-й Вятский переулок    NaN    NaN
18       5-я Соколиной горы улица     19    NaN
19       5-я Соколиной горы улица     25    NaN

In [8]:
arr = df_adress.to_numpy()
type(arr[19])

numpy.ndarray

In [9]:
df_adress.values.tolist()

[['16-я Парковая улица', nan, nan],
 ['1-й Паловский переулок', nan, nan],
 ['1-я Аэропортовская улица', nan, nan],
 ['1-я Владимирская улица', nan, nan],
 ['1-я Вольская улица', nan, nan],
 ['1-я Останкинская улица', nan, nan],
 ['26 Бакинских Комиссаров улица', nan, nan],
 ['2-й Стрелецкий переулок', nan, nan],
 ['2-й Тушинский проезд', nan, nan],
 ['2-я Владимирская улица', ' 19', nan],
 ['2-я Владимирская улица', ' 21', nan],
 ['2-я Звенигородская улица', nan, nan],
 ['2-я Кабельная улица', nan, nan],
 ['2-я Останкинская улица', nan, nan],
 ['3-я Гражданская улица', nan, nan],
 ['40 лет Октября проспект', ' 19', nan],
 ['40 лет Октября проспект', ' 4', nan],
 ['4-й Вятский переулок', nan, nan],
 ['5-я Соколиной горы улица', ' 19', nan],
 ['5-я Соколиной горы улица', ' 25', nan],
 ['6-я Кожуховская улица', nan, nan],
 ['800-летия Москвы улица', ' 1', nan],
 ['800-летия Москвы улица', ' 24', nan],
 ['9-я Парковая улица', nan, nan],
 ['9-я Соколиной Горы улица', nan, nan],
 ['Абрамцев

In [13]:
df_adress = df_adress.replace(np.nan, '', regex=True)
arr = df_adress.values.tolist()

In [15]:
len(arr)

465

In [16]:
google_ad = []
for i in range(0, len(arr)):
    google_ad.append(' '.join(arr[i]))
google_ad

['16-я Парковая улица  ',
 '1-й Паловский переулок  ',
 '1-я Аэропортовская улица  ',
 '1-я Владимирская улица  ',
 '1-я Вольская улица  ',
 '1-я Останкинская улица  ',
 '26 Бакинских Комиссаров улица  ',
 '2-й Стрелецкий переулок  ',
 '2-й Тушинский проезд  ',
 '2-я Владимирская улица  19 ',
 '2-я Владимирская улица  21 ',
 '2-я Звенигородская улица  ',
 '2-я Кабельная улица  ',
 '2-я Останкинская улица  ',
 '3-я Гражданская улица  ',
 '40 лет Октября проспект  19 ',
 '40 лет Октября проспект  4 ',
 '4-й Вятский переулок  ',
 '5-я Соколиной горы улица  19 ',
 '5-я Соколиной горы улица  25 ',
 '6-я Кожуховская улица  ',
 '800-летия Москвы улица  1 ',
 '800-летия Москвы улица  24 ',
 '9-я Парковая улица  ',
 '9-я Соколиной Горы улица  ',
 'Абрамцевская улица  ',
 'Авангардная улица  ',
 'Авиаконструктора Миля улица  4 ',
 'Авиаконструктора Миля улица  7 ',
 'Авиаторов улица  ',
 'Академика Анохина улица  ',
 'Академика Арцимовича улица  ',
 'Академика Павлова улица  ',
 'Академика Челом

In [25]:
latitudes = []
longitudes = []   

In [26]:
for i in range(0, len(google_ad)):
    coords = gmaps.geocode(google_ad[i])
    long = coords[0]['geometry']['location'] ['lng']
    lat = coords[0]['geometry']['location'] ['lat']
    longitudes.append(long)
    latitudes.append(lat)
    

In [27]:
len(longitudes)

465

In [30]:
#добавляем новые колонкм
df_adress['Latitude'] = latitudes
df_adress['Longitude'] = longitudes
df_adress

part1  part2  part3   Latitude  Longitude
0         16-я Парковая улица                55.801469  37.829487
1      1-й Паловский переулок                55.716500  37.631080
2    1-я Аэропортовская улица                55.800940  37.536184
3      1-я Владимирская улица                55.753999  37.777209
4          1-я Вольская улица                55.683334  37.921765
..                        ...    ...    ...        ...        ...
460         Ярославское шоссе      6         55.902848  37.760847
461           Ярцевская улица                55.740173  37.415197
462            Ясеневая улица     31         55.605198  37.738054
463            Ясеневая улица     39         55.606345  37.741936
464              Ясный проезд                55.873988  37.625188

[465 rows x 5 columns]

In [32]:
#saving all data back to csv file
df_adress.to_csv('file_name.csv', encoding='utf-8')

In [34]:

from itertools import tee

In [26]:
import googlemaps
from datetime import datetime

gmaps = googlemaps.Client(key='myAPIkey')


In [62]:
import time
from progress.bar import IncrementalBar



In [48]:
#матрица расстояний
#dist_matrix = np.array([[0] * 465 for i in range(l)])

#time matrix
#duration_matrix = np.array([[0] * 465 for i in range(l)])


In [39]:
import time
from tqdm.auto import tqdm

In [47]:
#считываем матрицу расстояния и времени
distance_matrix = np.loadtxt('distances.csv', delimiter=',')
duration_matrix = np.loadtxt('durations.csv', delimiter=',')

In [45]:
pbar = tqdm(total = 160000)
for i in range(0, 464):
    for j in range(0, 464):
        pbar.update(1)
        if distance_matrix[i][j] == 0:
            d = gmaps.distance_matrix(google_ad[i], google_ad[j])['rows'][0]['elements'][0]
            distance_matrix[i][j] = d['distance']['value']
            duration_matrix[i][j] = d['duration']['value']

In [95]:
print(dist_matrix)

[[    0 23276 32470 ... 31449 31713 23222]
 [20056     0 18473 ... 18102 18365 21996]
 [43738 15213     0 ... 32544 32808 15857]
 ...
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]]


In [ ]:
#сохраняем результаты в cvc таблички

#np.savetxt("distances.csv", distance_matrix, delimiter=",")
#np.savetxt("durations.csv", duration_matrix, delimiter=",")
#cvc with durations